### ISSUE TITLE
Is there any tool that can extract JS, HTML and CSS from a Ractive component?

### ISSUE THREAD

**Issue by jaygel179** [ractivejs/rvc#17]
I would like to know if there's an existing tool that can extract js/html/css part from a ractive component?

``` html
<div>
  ...
</div>


<style>
  ...
</style>


<script>
  component.exports = {
    ...
  }
</script>
```

If none then how possible it is to do?
Basically I want to create a tool that for example extracts the js part of a component into a  file, run jsLint to check the code validity and have it integrated with CI.

Thanks in advance.

**Comment by fskreuz** [comment]
For the HTML part, you don't really need to extract the HTML. A Ractive component is valid HTML to start with (minus the `<html>`, `<body>` etc.). You can configure your linter to ignore those (if possible), or wrap the entire component in `<html><body>[component source]</body></html>` before handing it over to the linter.

To extract the CSS and JS, you can use [rcu](https://github.com/ractivejs/rcu). You can use the [`parse`](https://github.com/ractivejs/rcu#rcuparse-source-) function to get the CSS and JS parts of the component in string form. You can then pass it on to their respective linters.

**Comment by jaygel179** [comment]
Thanks @fskreuz! will close this issue.
