### ISSUE TITLE
{{else}} breaks after optimisation

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/rvc#7]
After adding an if-else-block in clock.html, the optimised version fails with
"Uncaught TypeError: Cannot read property 'replace' of undefined"

After updating to 0.6.1 it fails with
"Uncaught TypeError: Cannot read property 'length' of undefined"
in ExpressionResolver, where it reads expression.r.length.

The unoptimised version works as expected, as does the optimised one when no {{else}} is used.

**Comment by aphitiel** [comment]
It works here when I remove the part of tosource() that returns '{$circularReference:1}' - currently line 547 in rvc.js

More information: clock.html was modified like this:
```html
      {{#if date.getSeconds() % 2}}
  			<line class='second-counterweight' y1='33' y2='5'/>
      {{else}}
  			<line class='second-counterweight' y1='10' y2='3'/>
      {{/if}}
```

With the else-clause, the optimized template differs like this:
optimized template, prettyfied:
```javascript
...
								{
									"t": 4,
									"n": 51,
									"f": [
										{
											"t": 7,
											"e": "line",
											"a": {
												"class": "second-counterweight",
												"y1": "33",
												"y2": "5"
											}
										}
									],
									"x": {
										"$circularReference": 1
									}
								}
```

clock.template:
```javascript
...
							{
								"t": 4,
								"n": 51,
								"f": [
									{
										"t": 7,
										"e": "line",
										"a": {
											"class": "second-counterweight",
											"y1": "10",
											"y2": "3"
										}
									}
								],
								"x": {
									"r": [
										"date"
									],
									"s": "_0.getSeconds()%2"
								}
							}
```

**Comment by sabob** [comment]
Just ran into this issue myself but it seems to be fixed in the latest version of Ractive:
http://cdn.ractivejs.org/edge/ractive.js

**Comment by aphitiel** [comment]
Confirmed, thanks! BTW, how did you get around 'Mismatched template version!'?

**Comment by sabob** [comment]
I had to change this line in rvc:
if ( parsed.v !== 1 ) {
to: 
if ( parsed.v !== 3 ) {

**Comment by martypdx** [comment]
I'm thinking the logic should specify a _minimum_ version so it can be forward compatible:

```js
if ( !parsed.v || parsed.v < 1 ) {
```
