### ISSUE TITLE
Error: Mismatched template version! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app

### ISSUE THREAD

**Issue by timshannon** [ractivejs/rvc#9]
I was checking out the edge version of Ractive, and was unable to rebuild my RVC based components.  It looks like RVC is still checking for version 1 (https://github.com/ractivejs/rvc/blob/master/rvc.js#L237), which is fine, I was just curious of a couple things.  

When do you think we'll get a version of RVC for template v3?
Should RVC even care about the template version?  Doesn't it rely on ractive to handle all the template processing?

**Comment by martypdx** [comment]
Seems to be the day for this question, see https://github.com/ractivejs/rvc/issues/7#issuecomment-75072419 for my opinion

**Comment by martypdx** [comment]
But more broadly, yes it would ideally be independent from the version of ractive.
